project:
  type: website

website:
  title: "BaselDataScience"
  repo-url: https://github.com/baseldatascience/baseldatascience.github.io
  repo-actions: [source, issue]
  open-graph: true 
  navbar:
    background: "#eeeeee"
    title-block-banner: baseldatasciencelogo.jpeg
    right:
      - icon: github
        aria-label: github
        href: https://github.com/baseldatascience/baseldatascience.github.io
      - icon: "chat-right-text"
        aria-label: linkedIn
        href: https://www.linkedin.com/groups/12870553/
        
format:
  html:
    css: styles.css
